all: line-plot-01  line-plot-02  lr00  lr01  lr02  lr03  lr04  lr05

line-plot-01: line-plot-01.c
	cc -o line-plot-01 line-plot-01.c 

line-plot-02: line-plot-02.c
	cc -o line-plot-02 line-plot-02.c -lm

lr00: lr00.c
	cc -o lr00 lr00.c 

lr01: lr01.c
	cc -o lr01 lr01.c 

lr02: lr02.c
	cc -o lr02 lr02.c -lm

lr03: lr03.c
	cc -o lr03 lr03.c -lm

lr04: lr04.c
	cc -o lr04 lr04.c -lm

lr05: lr05.c
	cc -o lr05 lr05.c -lm

clean:
	rm -f a.out *~ line-plot-01  line-plot-02  lr00  lr01  lr02  lr03  lr04  lr05
