all: optimisation_0 optimisation_1

optimisation_0: optimisation_0.c
	cc -o optimisation_0 optimisation_0.c -lm

optimisation_1: optimisation_1.c
	cc -o optimisation_1 optimisation_1.c -lm

clean:
	rm -f a.out *~ optimisation_0 optimisation_1

